### ISSUE TITLE
[2pt] Signup & Login pages - Front & Back Bees

### ISSUE THREAD

**Issue by jsug9** [jsug9/bee-bookings-front-end#13]
Create views for signing up as a user AND a different view for logging in as a user

**Comment by AKeeganDev** [comment]
I'll start the front end side of this. I plan to make the sign-up and log-in pages as popups that overlay the current site. I'll start with styling the way that I think it could look and we can figure out the submit logic to the database once we have the desired look figured out

**Comment by AKeeganDev** [comment]
Front-Bee side is complete. Here is a video of the UX

https://www.loom.com/share/ad6d96121002495fa3c97fd5897d39d1
